name: Generate Snake Animation

on:
  schedule:
    # Run once a day
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Download the repository content
      - name: Checkout
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: Anilnayak126
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Upload the output snake image to the repository
      - name: Commit and push the snake
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
